### ISSUE TITLE
Please do not delete container.php before new major release

### ISSUE THREAD

**Issue by Lewiscowles1986** [edhaase/slim-skeleton#6]
So keeping container.php, should help BC, and there are then notes for updating to 3.1 for 3.x users that may use an older Slim prior to major release of this skeleton. that's my thinking anyway, based upon #5

**Comment by edhaase** [comment]
Well, in order to use AppContainer we'll need 3.1, so if I'm following correctly I want to delete container.php, update to 3.1 (replacing the lock file and verifying deps), and if it all works, by semantic versioning that would this repo's 2.0.0 release.

**Comment by Lewiscowles1986** [comment]
:+1: 10/4
