### ISSUE TITLE
AppContainer Update

### ISSUE THREAD

**Issue by Lewiscowles1986** [edhaase/slim-skeleton#7]
I have a separate PR to update AppContainer, I don't want to bundle it with the switch to AppContainer, unless you think that's better, but basically `container.php` seems to add some deps that are not provisioned for in `AppContainer`. Changes can be seen at https://github.com/Lewiscowles1986/slim-skeleton/tree/patch-3

**Comment by edhaase** [comment]
Separate PRs are fine, I think. I had kind of ignored AppContainer until 3.1, wasn't expecting that to drop _this morning_. But I'm glad it did.

**Comment by Lewiscowles1986** [comment]
:+1:
